/**********************************************************************
*
* clk_gen controller C MACRO generated by easy-chip
* generated in Wed, 25 Jul 2018 04:42:18 GMT
*
******************************************************************/

#ifndef _CLK_GEN_MACRO_H_
#define _CLK_GEN_MACRO_H_
#include "cdl_types.h"
#include "hw_maps.h"

//#define CLK_GEN_BASE_ADDR 0x0
#define pll1_in_218_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x0
#define pll1_out_div5_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x4
#define pll1_out_div3_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x8
#define pll1_out_div2_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0xC
#define pll1_out_div125_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x10
#define pll1_out_spi_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x14
#define fclk_48m_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x18
#define fclk_24m_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x1C
#define fclk_12m_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x20
#define pll2_in_219_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x24
#define pll3_in_220_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x28
#define pll3_out_div2_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x2C
#define pll3_out_div20_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x30
#define dsp_clk_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x34
#define axi_clk_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x38
#define ahb_clk_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x3C
#define apb_clk_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x40
#define i2sadc_bclk_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x44
#define i2s0_in_bclk_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x48
#define i2s0_in_lrck_345_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x4C
#define i2s1_in_bclk_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x50
#define i2s1_in_lrck_346_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x54
#define i2sadc_bclk_icg_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x58
#define i2sadc_lrck_internal_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x5C
#define Frdiv0_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x60
#define pclk_timclk_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x64
#define pclk_wdogclk_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x68
#define dsp0_clk_295_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x6C
#define dsp1_clk_296_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x70
#define SHRM0_CLK_122_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x74
#define SHRM1_CLK_123_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x78
#define SHRM2_CLK_124_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x7C
#define SHRM3_CLK_125_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x80
#define vad_mem_clk_129_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x84
#define dmac_core_clock_115_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x88
#define DMA_aclk_m1_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x8C
#define DMA_hclk_115_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x90
#define gpio_PCLK_140_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x94
#define wdt_PCLK_139_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x98
#define wdt_WDOGCLK_139_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x9C
#define i2c0_pclk_131_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0xA0
#define i2c0_ic_clk_131_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0xA4
#define i2c1_pclk_132_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0xA8
#define i2c1_ic_clk_132_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0xAC
#define SPI_PCLK_130_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0xB0
#define SPI_SSPCLK_130_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0xB4
#define timer_PCLK_141_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0xB8
#define timer_TIMCLK_141_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0xBC
#define apbucp_pclk_292_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0xC0
#define uart0_pclk_136_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0xC4
#define uart0_sclk_136_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0xC8
#define uart1_pclk_137_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0xCC
#define uart1_sclk_137_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0xD0
#define USB_HCLK_161_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0xD4
#define USB_CLK_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0xD8
#define USB_FCLK_161_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0xDC
#define i2sadc_pclk_126_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0xE0
#define i2sadc_lrck_126_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0xE4
#define i2sdac_pclk_127_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0xE8
#define i2s1_pclk_128_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0xEC
#define i2svad_pclk_129_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0xF0
#define i2svad_lrck_129_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0xF4
#define ACDC_MCLK_229_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0xF8
#define ptc_pclk_138_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0xFC
#define usb_ram_clk_232_ctrl_REG_ADDR CLK_GEN_BASE_ADDR + 0x100

#define _ENABLE_CLOCK_pll1_in_218_ { \
}

#define _SWITCH_CLOCK_pll1_in_218_SOURCE_osc_clk { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(pll1_in_218_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x1000000; \
	_clk_gen_macro_read_value_ |= 0x0<<24; \
MA_OUTW(pll1_in_218_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_pll1_in_218_SOURCE_i2s2_pad_mclk { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(pll1_in_218_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x1000000; \
	_clk_gen_macro_read_value_ |= 0x1<<24; \
MA_OUTW(pll1_in_218_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_pll1_out_div5_ { \
}

#define _DIVIDE_CLOCK_pll1_out_div5_(div) { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(pll1_out_div5_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x7; \
	_clk_gen_macro_read_value_ |= div; \
MA_OUTW(pll1_out_div5_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_pll1_out_div3_ { \
}

#define _DIVIDE_CLOCK_pll1_out_div3_(div) { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(pll1_out_div3_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x7; \
	_clk_gen_macro_read_value_ |= div; \
MA_OUTW(pll1_out_div3_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_pll1_out_div2_ { \
}

#define _DIVIDE_CLOCK_pll1_out_div2_(div) { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(pll1_out_div2_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x7; \
	_clk_gen_macro_read_value_ |= div; \
MA_OUTW(pll1_out_div2_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_pll1_out_div125_ { \
}

#define _DIVIDE_CLOCK_pll1_out_div125_(div) { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(pll1_out_div125_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x1F; \
	_clk_gen_macro_read_value_ |= div; \
MA_OUTW(pll1_out_div125_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_pll1_out_spi_ { \
}

#define _DIVIDE_CLOCK_pll1_out_spi_(div) { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(pll1_out_spi_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3F; \
	_clk_gen_macro_read_value_ |= div; \
MA_OUTW(pll1_out_spi_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_fclk_48m_ { \
}

#define _DIVIDE_CLOCK_fclk_48m_(div) { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(fclk_48m_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0xF; \
	_clk_gen_macro_read_value_ |= div; \
MA_OUTW(fclk_48m_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_fclk_24m_ { \
}

#define _DIVIDE_CLOCK_fclk_24m_(div) { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(fclk_24m_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x1F; \
	_clk_gen_macro_read_value_ |= div; \
MA_OUTW(fclk_24m_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_fclk_12m_ { \
}

#define _DIVIDE_CLOCK_fclk_12m_(div) { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(fclk_12m_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x1F; \
	_clk_gen_macro_read_value_ |= div; \
MA_OUTW(fclk_12m_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_pll2_in_219_ { \
}

#define _SWITCH_CLOCK_pll2_in_219_SOURCE_osc_clk { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(pll2_in_219_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x0<<24; \
MA_OUTW(pll2_in_219_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_pll2_in_219_SOURCE_fclk_48m { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(pll2_in_219_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x1<<24; \
MA_OUTW(pll2_in_219_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_pll2_in_219_SOURCE_i2s2_pad_mclk { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(pll2_in_219_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x2<<24; \
MA_OUTW(pll2_in_219_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_pll3_in_220_ { \
}

#define _SWITCH_CLOCK_pll3_in_220_SOURCE_osc_clk { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(pll3_in_220_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x0<<24; \
MA_OUTW(pll3_in_220_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_pll3_in_220_SOURCE_pll1_out_div125 { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(pll3_in_220_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x1<<24; \
MA_OUTW(pll3_in_220_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_pll3_in_220_SOURCE_i2s2_pad_mclk { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(pll3_in_220_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x2<<24; \
MA_OUTW(pll3_in_220_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_pll3_out_div2_ { \
}

#define _DIVIDE_CLOCK_pll3_out_div2_(div) { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(pll3_out_div2_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x7; \
	_clk_gen_macro_read_value_ |= div; \
MA_OUTW(pll3_out_div2_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_pll3_out_div20_ { \
}

#define _DIVIDE_CLOCK_pll3_out_div20_(div) { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(pll3_out_div20_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0xF; \
	_clk_gen_macro_read_value_ |= div; \
MA_OUTW(pll3_out_div20_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_dsp_clk_ { \
}

#define _SWITCH_CLOCK_dsp_clk_SOURCE_osc_clk { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(dsp_clk_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x0<<24; \
MA_OUTW(dsp_clk_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_dsp_clk_SOURCE_pll2_out { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(dsp_clk_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x1<<24; \
MA_OUTW(dsp_clk_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_dsp_clk_SOURCE_pll1_out_div3 { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(dsp_clk_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x2<<24; \
MA_OUTW(dsp_clk_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_dsp_clk_SOURCE_fclk_48m { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(dsp_clk_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x3<<24; \
MA_OUTW(dsp_clk_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DIVIDE_CLOCK_dsp_clk_(div) { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(dsp_clk_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x1F; \
	_clk_gen_macro_read_value_ |= div; \
MA_OUTW(dsp_clk_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_axi_clk_ { \
}

#define _DIVIDE_CLOCK_axi_clk_(div) { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(axi_clk_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x1F; \
	_clk_gen_macro_read_value_ |= div; \
MA_OUTW(axi_clk_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_ahb_clk_ { \
}

#define _DIVIDE_CLOCK_ahb_clk_(div) { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(ahb_clk_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x1F; \
	_clk_gen_macro_read_value_ |= div; \
MA_OUTW(ahb_clk_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_apb_clk_ { \
}

#define _DIVIDE_CLOCK_apb_clk_(div) { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(apb_clk_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x1F; \
	_clk_gen_macro_read_value_ |= div; \
MA_OUTW(apb_clk_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_i2sadc_bclk_ { \
}

#define _SWITCH_CLOCK_i2sadc_bclk_SOURCE_osc_aon_clk { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2sadc_bclk_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x1000000; \
	_clk_gen_macro_read_value_ |= 0x0<<24; \
MA_OUTW(i2sadc_bclk_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_i2sadc_bclk_SOURCE_pll1_out_div5 { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2sadc_bclk_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x1000000; \
	_clk_gen_macro_read_value_ |= 0x1<<24; \
MA_OUTW(i2sadc_bclk_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DIVIDE_CLOCK_i2sadc_bclk_(div) { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2sadc_bclk_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x1FF; \
	_clk_gen_macro_read_value_ |= div; \
MA_OUTW(i2sadc_bclk_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_i2s0_in_bclk_ { \
}

#define _DIVIDE_CLOCK_i2s0_in_bclk_(div) { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2s0_in_bclk_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3F; \
	_clk_gen_macro_read_value_ |= div; \
MA_OUTW(i2s0_in_bclk_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_i2s0_in_lrck_345_ { \
}

#define _DIVIDE_CLOCK_i2s0_in_lrck_345_(div) { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2s0_in_lrck_345_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0xFF; \
	_clk_gen_macro_read_value_ |= div; \
MA_OUTW(i2s0_in_lrck_345_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_i2s1_in_bclk_ { \
}

#define _DIVIDE_CLOCK_i2s1_in_bclk_(div) { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2s1_in_bclk_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x1FF; \
	_clk_gen_macro_read_value_ |= div; \
MA_OUTW(i2s1_in_bclk_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_i2s1_in_lrck_346_ { \
}

#define _DIVIDE_CLOCK_i2s1_in_lrck_346_(div) { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2s1_in_lrck_346_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x1FF; \
	_clk_gen_macro_read_value_ |= div; \
MA_OUTW(i2s1_in_lrck_346_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_i2sadc_bclk_icg_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2sadc_bclk_icg_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(i2sadc_bclk_icg_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_i2sadc_bclk_icg_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2sadc_bclk_icg_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(i2sadc_bclk_icg_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_i2sadc_lrck_internal_ { \
}

#define _DIVIDE_CLOCK_i2sadc_lrck_internal_(div) { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2sadc_lrck_internal_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x1FF; \
	_clk_gen_macro_read_value_ |= div; \
MA_OUTW(i2sadc_lrck_internal_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_Frdiv0_ { \
}

#define _SWITCH_CLOCK_Frdiv0_SOURCE_osc_clk { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(Frdiv0_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x0<<24; \
MA_OUTW(Frdiv0_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_Frdiv0_SOURCE_pll1_out_div2 { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(Frdiv0_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x1<<24; \
MA_OUTW(Frdiv0_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_Frdiv0_SOURCE_pll2_out { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(Frdiv0_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x2<<24; \
MA_OUTW(Frdiv0_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_Frdiv0_SOURCE_fclk_48m { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(Frdiv0_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x3<<24; \
MA_OUTW(Frdiv0_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DIVIDE_CLOCK_Frdiv0_(div) { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(Frdiv0_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0xFFFF; \
	_clk_gen_macro_read_value_ |= div; \
MA_OUTW(Frdiv0_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_pclk_timclk_ { \
}

#define _DIVIDE_CLOCK_pclk_timclk_(div) { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(pclk_timclk_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0xFF; \
	_clk_gen_macro_read_value_ |= div; \
MA_OUTW(pclk_timclk_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_pclk_wdogclk_ { \
}

#define _DIVIDE_CLOCK_pclk_wdogclk_(div) { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(pclk_wdogclk_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0xFF; \
	_clk_gen_macro_read_value_ |= div; \
MA_OUTW(pclk_wdogclk_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_dsp0_clk_295_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(dsp0_clk_295_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(dsp0_clk_295_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_dsp0_clk_295_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(dsp0_clk_295_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(dsp0_clk_295_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_dsp1_clk_296_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(dsp1_clk_296_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(dsp1_clk_296_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_dsp1_clk_296_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(dsp1_clk_296_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(dsp1_clk_296_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_SHRM0_CLK_122_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(SHRM0_CLK_122_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(SHRM0_CLK_122_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_SHRM0_CLK_122_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(SHRM0_CLK_122_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(SHRM0_CLK_122_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_SHRM1_CLK_123_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(SHRM1_CLK_123_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(SHRM1_CLK_123_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_SHRM1_CLK_123_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(SHRM1_CLK_123_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(SHRM1_CLK_123_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_SHRM2_CLK_124_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(SHRM2_CLK_124_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(SHRM2_CLK_124_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_SHRM2_CLK_124_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(SHRM2_CLK_124_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(SHRM2_CLK_124_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_SHRM3_CLK_125_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(SHRM3_CLK_125_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(SHRM3_CLK_125_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_SHRM3_CLK_125_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(SHRM3_CLK_125_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(SHRM3_CLK_125_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_vad_mem_clk_129_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(vad_mem_clk_129_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(vad_mem_clk_129_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_vad_mem_clk_129_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(vad_mem_clk_129_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(vad_mem_clk_129_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_vad_mem_clk_129_SOURCE_axi_clk { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(vad_mem_clk_129_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x1000000; \
	_clk_gen_macro_read_value_ |= 0x0<<24; \
MA_OUTW(vad_mem_clk_129_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_vad_mem_clk_129_SOURCE_i2sadc_bclk { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(vad_mem_clk_129_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x1000000; \
	_clk_gen_macro_read_value_ |= 0x1<<24; \
MA_OUTW(vad_mem_clk_129_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_dmac_core_clock_115_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(dmac_core_clock_115_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(dmac_core_clock_115_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_dmac_core_clock_115_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(dmac_core_clock_115_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(dmac_core_clock_115_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_DMA_aclk_m1_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(DMA_aclk_m1_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(DMA_aclk_m1_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_DMA_aclk_m1_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(DMA_aclk_m1_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(DMA_aclk_m1_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_DMA_hclk_115_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(DMA_hclk_115_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(DMA_hclk_115_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_DMA_hclk_115_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(DMA_hclk_115_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(DMA_hclk_115_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_gpio_PCLK_140_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(gpio_PCLK_140_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(gpio_PCLK_140_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_gpio_PCLK_140_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(gpio_PCLK_140_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(gpio_PCLK_140_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_gpio_PCLK_140_SOURCE_apb_clk { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(gpio_PCLK_140_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x1000000; \
	_clk_gen_macro_read_value_ |= 0x0<<24; \
MA_OUTW(gpio_PCLK_140_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_gpio_PCLK_140_SOURCE_osc_aon_clk { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(gpio_PCLK_140_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x1000000; \
	_clk_gen_macro_read_value_ |= 0x1<<24; \
MA_OUTW(gpio_PCLK_140_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DIVIDE_CLOCK_gpio_PCLK_140_(div) { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(gpio_PCLK_140_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3FF; \
	_clk_gen_macro_read_value_ |= div; \
MA_OUTW(gpio_PCLK_140_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_wdt_PCLK_139_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(wdt_PCLK_139_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(wdt_PCLK_139_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_wdt_PCLK_139_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(wdt_PCLK_139_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(wdt_PCLK_139_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_wdt_WDOGCLK_139_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(wdt_WDOGCLK_139_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(wdt_WDOGCLK_139_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_wdt_WDOGCLK_139_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(wdt_WDOGCLK_139_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(wdt_WDOGCLK_139_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_i2c0_pclk_131_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2c0_pclk_131_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(i2c0_pclk_131_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_i2c0_pclk_131_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2c0_pclk_131_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(i2c0_pclk_131_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_i2c0_ic_clk_131_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2c0_ic_clk_131_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(i2c0_ic_clk_131_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_i2c0_ic_clk_131_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2c0_ic_clk_131_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(i2c0_ic_clk_131_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_i2c0_ic_clk_131_SOURCE_osc_clk { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2c0_ic_clk_131_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x0<<24; \
MA_OUTW(i2c0_ic_clk_131_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_i2c0_ic_clk_131_SOURCE_fclk_48m { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2c0_ic_clk_131_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x1<<24; \
MA_OUTW(i2c0_ic_clk_131_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_i2c0_ic_clk_131_SOURCE_fclk_24m { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2c0_ic_clk_131_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x2<<24; \
MA_OUTW(i2c0_ic_clk_131_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_i2c0_ic_clk_131_SOURCE_Frdiv0 { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2c0_ic_clk_131_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x3<<24; \
MA_OUTW(i2c0_ic_clk_131_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_i2c1_pclk_132_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2c1_pclk_132_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(i2c1_pclk_132_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_i2c1_pclk_132_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2c1_pclk_132_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(i2c1_pclk_132_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_i2c1_ic_clk_132_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2c1_ic_clk_132_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(i2c1_ic_clk_132_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_i2c1_ic_clk_132_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2c1_ic_clk_132_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(i2c1_ic_clk_132_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_i2c1_ic_clk_132_SOURCE_osc_clk { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2c1_ic_clk_132_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x0<<24; \
MA_OUTW(i2c1_ic_clk_132_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_i2c1_ic_clk_132_SOURCE_fclk_48m { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2c1_ic_clk_132_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x1<<24; \
MA_OUTW(i2c1_ic_clk_132_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_i2c1_ic_clk_132_SOURCE_fclk_24m { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2c1_ic_clk_132_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x2<<24; \
MA_OUTW(i2c1_ic_clk_132_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_i2c1_ic_clk_132_SOURCE_Frdiv0 { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2c1_ic_clk_132_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x3<<24; \
MA_OUTW(i2c1_ic_clk_132_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_SPI_PCLK_130_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(SPI_PCLK_130_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(SPI_PCLK_130_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_SPI_PCLK_130_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(SPI_PCLK_130_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(SPI_PCLK_130_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_SPI_SSPCLK_130_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(SPI_SSPCLK_130_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(SPI_SSPCLK_130_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_SPI_SSPCLK_130_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(SPI_SSPCLK_130_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(SPI_SSPCLK_130_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_SPI_SSPCLK_130_SOURCE_osc_clk { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(SPI_SSPCLK_130_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x0<<24; \
MA_OUTW(SPI_SSPCLK_130_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_SPI_SSPCLK_130_SOURCE_fclk_48m { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(SPI_SSPCLK_130_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x1<<24; \
MA_OUTW(SPI_SSPCLK_130_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_SPI_SSPCLK_130_SOURCE_fclk_24m { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(SPI_SSPCLK_130_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x2<<24; \
MA_OUTW(SPI_SSPCLK_130_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_SPI_SSPCLK_130_SOURCE_pll1_out_spi { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(SPI_SSPCLK_130_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x3<<24; \
MA_OUTW(SPI_SSPCLK_130_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_timer_PCLK_141_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(timer_PCLK_141_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(timer_PCLK_141_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_timer_PCLK_141_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(timer_PCLK_141_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(timer_PCLK_141_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_timer_TIMCLK_141_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(timer_TIMCLK_141_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(timer_TIMCLK_141_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_timer_TIMCLK_141_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(timer_TIMCLK_141_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(timer_TIMCLK_141_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_apbucp_pclk_292_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(apbucp_pclk_292_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(apbucp_pclk_292_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_apbucp_pclk_292_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(apbucp_pclk_292_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(apbucp_pclk_292_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_uart0_pclk_136_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(uart0_pclk_136_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(uart0_pclk_136_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_uart0_pclk_136_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(uart0_pclk_136_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(uart0_pclk_136_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_uart0_sclk_136_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(uart0_sclk_136_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(uart0_sclk_136_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_uart0_sclk_136_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(uart0_sclk_136_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(uart0_sclk_136_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_uart0_sclk_136_SOURCE_osc_clk { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(uart0_sclk_136_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x0<<24; \
MA_OUTW(uart0_sclk_136_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_uart0_sclk_136_SOURCE_fclk_48m { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(uart0_sclk_136_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x1<<24; \
MA_OUTW(uart0_sclk_136_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_uart0_sclk_136_SOURCE_fclk_24m { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(uart0_sclk_136_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x2<<24; \
MA_OUTW(uart0_sclk_136_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_uart0_sclk_136_SOURCE_Frdiv0 { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(uart0_sclk_136_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x3<<24; \
MA_OUTW(uart0_sclk_136_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_uart1_pclk_137_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(uart1_pclk_137_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(uart1_pclk_137_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_uart1_pclk_137_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(uart1_pclk_137_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(uart1_pclk_137_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_uart1_sclk_137_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(uart1_sclk_137_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(uart1_sclk_137_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_uart1_sclk_137_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(uart1_sclk_137_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(uart1_sclk_137_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_uart1_sclk_137_SOURCE_osc_clk { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(uart1_sclk_137_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x0<<24; \
MA_OUTW(uart1_sclk_137_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_uart1_sclk_137_SOURCE_fclk_48m { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(uart1_sclk_137_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x1<<24; \
MA_OUTW(uart1_sclk_137_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_uart1_sclk_137_SOURCE_fclk_24m { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(uart1_sclk_137_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x2<<24; \
MA_OUTW(uart1_sclk_137_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_uart1_sclk_137_SOURCE_Frdiv0 { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(uart1_sclk_137_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x3<<24; \
MA_OUTW(uart1_sclk_137_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_USB_HCLK_161_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(USB_HCLK_161_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(USB_HCLK_161_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_USB_HCLK_161_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(USB_HCLK_161_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(USB_HCLK_161_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_USB_CLK_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(USB_CLK_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(USB_CLK_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_USB_CLK_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(USB_CLK_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(USB_CLK_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_USB_FCLK_161_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(USB_FCLK_161_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(USB_FCLK_161_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_USB_FCLK_161_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(USB_FCLK_161_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(USB_FCLK_161_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_i2sadc_pclk_126_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2sadc_pclk_126_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(i2sadc_pclk_126_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_i2sadc_pclk_126_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2sadc_pclk_126_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(i2sadc_pclk_126_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_i2sadc_lrck_126_ { \
}

#define _SWITCH_CLOCK_i2sadc_lrck_126_SOURCE_i2sadc_lrck_internal { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2sadc_lrck_126_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x1000000; \
	_clk_gen_macro_read_value_ |= 0x0<<24; \
MA_OUTW(i2sadc_lrck_126_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_i2sadc_lrck_126_SOURCE_i2sadc_lrck_internal_neg { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2sadc_lrck_126_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x1000000; \
	_clk_gen_macro_read_value_ |= 0x1<<24; \
MA_OUTW(i2sadc_lrck_126_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_i2sdac_pclk_127_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2sdac_pclk_127_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(i2sdac_pclk_127_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_i2sdac_pclk_127_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2sdac_pclk_127_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(i2sdac_pclk_127_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_i2s1_pclk_128_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2s1_pclk_128_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(i2s1_pclk_128_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_i2s1_pclk_128_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2s1_pclk_128_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(i2s1_pclk_128_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_i2svad_pclk_129_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2svad_pclk_129_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(i2svad_pclk_129_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_i2svad_pclk_129_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2svad_pclk_129_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(i2svad_pclk_129_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_i2svad_pclk_129_SOURCE_apb_clk { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2svad_pclk_129_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x1000000; \
	_clk_gen_macro_read_value_ |= 0x0<<24; \
MA_OUTW(i2svad_pclk_129_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_i2svad_pclk_129_SOURCE_osc_aon_clk { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2svad_pclk_129_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x1000000; \
	_clk_gen_macro_read_value_ |= 0x1<<24; \
MA_OUTW(i2svad_pclk_129_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_i2svad_lrck_129_ { \
}

#define _SWITCH_CLOCK_i2svad_lrck_129_SOURCE_i2sadc_lrck_internal { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2svad_lrck_129_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x1000000; \
	_clk_gen_macro_read_value_ |= 0x0<<24; \
MA_OUTW(i2svad_lrck_129_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_i2svad_lrck_129_SOURCE_i2sadc_lrck_internal_neg { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(i2svad_lrck_129_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x1000000; \
	_clk_gen_macro_read_value_ |= 0x1<<24; \
MA_OUTW(i2svad_lrck_129_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_ACDC_MCLK_229_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(ACDC_MCLK_229_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(ACDC_MCLK_229_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_ACDC_MCLK_229_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(ACDC_MCLK_229_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(ACDC_MCLK_229_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_ACDC_MCLK_229_SOURCE_osc_aon_clk { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(ACDC_MCLK_229_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x0<<24; \
MA_OUTW(ACDC_MCLK_229_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_ACDC_MCLK_229_SOURCE_fclk_24m { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(ACDC_MCLK_229_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x1<<24; \
MA_OUTW(ACDC_MCLK_229_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _SWITCH_CLOCK_ACDC_MCLK_229_SOURCE_i2s2_mclk { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(ACDC_MCLK_229_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x3000000; \
	_clk_gen_macro_read_value_ |= 0x2<<24; \
MA_OUTW(ACDC_MCLK_229_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DIVIDE_CLOCK_ACDC_MCLK_229_(div) { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(ACDC_MCLK_229_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= ~0x1F; \
	_clk_gen_macro_read_value_ |= div; \
MA_OUTW(ACDC_MCLK_229_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_ptc_pclk_138_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(ptc_pclk_138_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(ptc_pclk_138_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_ptc_pclk_138_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(ptc_pclk_138_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(ptc_pclk_138_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _ENABLE_CLOCK_usb_ram_clk_232_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(usb_ram_clk_232_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ |= 0x80000000; \
	MA_OUTW(usb_ram_clk_232_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#define _DISABLE_CLOCK_usb_ram_clk_232_ { \
	uint32_t _clk_gen_macro_read_value_=MA_INW(usb_ram_clk_232_ctrl_REG_ADDR); \
	_clk_gen_macro_read_value_ &= 0x7FFFFFFF; \
	MA_OUTW(usb_ram_clk_232_ctrl_REG_ADDR,_clk_gen_macro_read_value_); \
}

#endif //_CLK_GEN_MACRO_H_
