/**********************************************************************
*
* pad_share controller C MACRO generated by easy-chip
* generated in Wed, 25 Jul 2018 04:42:19 GMT
*
******************************************************************/

#ifndef _PAD_SHARE_MACRO_H_
#define _PAD_SHARE_MACRO_H_
#include "cdl_types.h"
#include "hw_maps.h"

//#define PAD_SHARE_BASE_ADDR 0x0
#define pad_share_ctrl_0_REG_ADDR PAD_SHARE_BASE_ADDR + 0x0
#define pad_share_ctrl_1_REG_ADDR PAD_SHARE_BASE_ADDR + 0x4
#define pad_share_ctrl_2_REG_ADDR PAD_SHARE_BASE_ADDR + 0x8
#define pad_share_ctrl_3_REG_ADDR PAD_SHARE_BASE_ADDR + 0xC

#define _SET_PAD_PAD_TCK_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TCK_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x1; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TCK_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x2; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TCK_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x3; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TCK_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x4; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TCK_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x5; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TCK_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x6; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TCK_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x7; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TCK_PORT_REN(v) { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x8; \
	_pad_share_macro_read_value_ |= (v&0x1)<<3; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TMS_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TMS_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x10; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TMS_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x20; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TMS_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x30; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TMS_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x40; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TMS_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x50; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TMS_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x60; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TMS_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x70; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TMS_PORT_REN(v) { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x80; \
	_pad_share_macro_read_value_ |= (v&0x1)<<7; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TDO_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TDO_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x100; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TDO_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x200; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TDO_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x300; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TDO_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x400; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TDO_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x500; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TDO_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x600; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TDO_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x700; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TDO_PORT_REN(v) { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x800; \
	_pad_share_macro_read_value_ |= (v&0x1)<<11; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TDI_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TDI_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x1000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TDI_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x2000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TDI_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x3000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TDI_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x4000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TDI_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x5000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TDI_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x6000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TDI_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x7000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TDI_PORT_REN(v) { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x8000; \
	_pad_share_macro_read_value_ |= (v&0x1)<<15; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TRST_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TRST_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x10000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TRST_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x20000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TRST_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x30000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TRST_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x40000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TRST_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x50000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TRST_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x60000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TRST_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x70000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_TRST_PORT_REN(v) { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x80000; \
	_pad_share_macro_read_value_ |= (v&0x1)<<19; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_CLK_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_CLK_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x100000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_CLK_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x200000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_CLK_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x300000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_CLK_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x400000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_CLK_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x500000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_CLK_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x600000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_CLK_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x700000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_CLK_PORT_REN(v) { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x800000; \
	_pad_share_macro_read_value_ |= (v&0x1)<<23; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_CSN_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_CSN_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x1000000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_CSN_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x2000000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_CSN_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x3000000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_CSN_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x4000000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_CSN_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x5000000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_CSN_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x6000000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_CSN_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x7000000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_CSN_PORT_REN(v) { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x8000000; \
	_pad_share_macro_read_value_ |= (v&0x1)<<27; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_RXD_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_RXD_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x10000000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_RXD_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x20000000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_RXD_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x30000000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_RXD_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x40000000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_RXD_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x50000000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_RXD_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x60000000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_RXD_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x70000000; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_RXD_PORT_REN(v) { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_0_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x80000000; \
	_pad_share_macro_read_value_ |= (v&0x1)<<31; \
	MA_OUTW(pad_share_ctrl_0_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_TXD_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_TXD_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x1; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_TXD_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x2; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_TXD_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x3; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_TXD_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x4; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_TXD_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x5; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_TXD_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x6; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_TXD_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x7; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_SPI_TXD_PORT_REN(v) { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x8; \
	_pad_share_macro_read_value_ |= (v&0x1)<<3; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_UART0_RXD_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_UART0_RXD_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x10; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_UART0_RXD_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x20; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_UART0_RXD_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x30; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_UART0_RXD_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x40; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_UART0_RXD_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x50; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_UART0_RXD_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x60; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_UART0_RXD_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x70; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_UART0_RXD_PORT_REN(v) { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x80; \
	_pad_share_macro_read_value_ |= (v&0x1)<<7; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_UART0_TXD_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_UART0_TXD_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x100; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_UART0_TXD_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x200; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_UART0_TXD_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x300; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_UART0_TXD_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x400; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_UART0_TXD_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x500; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_UART0_TXD_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x600; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_UART0_TXD_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x700; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_UART0_TXD_PORT_REN(v) { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x800; \
	_pad_share_macro_read_value_ |= (v&0x1)<<11; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2CSSCL_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2CSSCL_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x1000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2CSSCL_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x2000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2CSSCL_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x3000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2CSSCL_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x4000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2CSSCL_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x5000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2CSSCL_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x6000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2CSSCL_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x7000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2CSSCL_PORT_REN(v) { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x8000; \
	_pad_share_macro_read_value_ |= (v&0x1)<<15; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2CSSDA_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2CSSDA_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x10000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2CSSDA_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x20000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2CSSDA_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x30000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2CSSDA_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x40000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2CSSDA_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x50000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2CSSDA_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x60000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2CSSDA_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x70000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2CSSDA_PORT_REN(v) { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x80000; \
	_pad_share_macro_read_value_ |= (v&0x1)<<19; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_GPIO0_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_GPIO0_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x100000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_GPIO0_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x200000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_GPIO0_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x300000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_GPIO0_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x400000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_GPIO0_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x500000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_GPIO0_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x600000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_GPIO0_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x700000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_GPIO0_PORT_REN(v) { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x800000; \
	_pad_share_macro_read_value_ |= (v&0x1)<<23; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_GPIO1_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_GPIO1_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x1000000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_GPIO1_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x2000000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_GPIO1_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x3000000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_GPIO1_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x4000000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_GPIO1_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x5000000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_GPIO1_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x6000000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_GPIO1_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x7000000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_GPIO1_PORT_REN(v) { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x8000000; \
	_pad_share_macro_read_value_ |= (v&0x1)<<27; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_PWM0_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_PWM0_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x10000000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_PWM0_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x20000000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_PWM0_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x30000000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_PWM0_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x40000000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_PWM0_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x50000000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_PWM0_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x60000000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_PWM0_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_1_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x70000000; \
	MA_OUTW(pad_share_ctrl_1_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_PWM1_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_PWM1_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x1; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_PWM1_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x2; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_PWM1_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x3; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_PWM1_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x4; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_PWM1_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x5; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_PWM1_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x6; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_PWM1_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x7; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_PWM2_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_PWM2_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x10; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_PWM2_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x20; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_PWM2_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x30; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_PWM2_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x40; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_PWM2_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x50; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_PWM2_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x60; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_PWM2_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x70; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK11_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK11_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x100; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK11_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x200; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK11_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x300; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK11_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x400; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK11_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x500; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK11_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x600; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK11_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x700; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK11_PORT_REN(v) { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x800; \
	_pad_share_macro_read_value_ |= (v&0x1)<<11; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK12_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK12_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x1000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK12_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x2000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK12_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x3000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK12_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x4000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK12_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x5000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK12_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x6000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK12_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x7000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK12_PORT_REN(v) { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x8000; \
	_pad_share_macro_read_value_ |= (v&0x1)<<15; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_IN1_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_IN1_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x10000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_IN1_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x20000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_IN1_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x30000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_IN1_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x40000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_IN1_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x50000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_IN1_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x60000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_IN1_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x70000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_IN1_PORT_REN(v) { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x80000; \
	_pad_share_macro_read_value_ |= (v&0x1)<<19; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK21_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK21_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x100000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK21_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x200000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK21_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x300000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK21_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x400000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK21_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x500000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK21_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x600000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK21_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x700000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK21_PORT_REN(v) { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x800000; \
	_pad_share_macro_read_value_ |= (v&0x1)<<23; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK22_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK22_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x1000000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK22_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x2000000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK22_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x3000000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK22_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x4000000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK22_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x5000000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK22_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x6000000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK22_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x7000000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_CLK22_PORT_REN(v) { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x8000000; \
	_pad_share_macro_read_value_ |= (v&0x1)<<27; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_IN2_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_IN2_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x10000000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_IN2_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x20000000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_IN2_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x30000000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_IN2_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x40000000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_IN2_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x50000000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_IN2_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x60000000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_IN2_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x70000000; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_DMIC_IN2_PORT_REN(v) { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_2_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x80000000; \
	_pad_share_macro_read_value_ |= (v&0x1)<<31; \
	MA_OUTW(pad_share_ctrl_2_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2SMIC_SBCLK_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2SMIC_SBCLK_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x1; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2SMIC_SBCLK_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x2; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2SMIC_SBCLK_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x3; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2SMIC_SBCLK_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x4; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2SMIC_SBCLK_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x5; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2SMIC_SBCLK_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x6; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2SMIC_SBCLK_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7; \
	_pad_share_macro_read_value_ |= 0x7; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2SMIC_SBCLK_PORT_REN(v) { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x8; \
	_pad_share_macro_read_value_ |= (v&0x1)<<3; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2SMIC_SLRO_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2SMIC_SLRO_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x10; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2SMIC_SLRO_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x20; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2SMIC_SLRO_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x30; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2SMIC_SLRO_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x40; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2SMIC_SLRO_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x50; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2SMIC_SLRO_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x60; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2SMIC_SLRO_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70; \
	_pad_share_macro_read_value_ |= 0x70; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2SMIC_SLRO_PORT_REN(v) { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x80; \
	_pad_share_macro_read_value_ |= (v&0x1)<<7; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2SMIC_SSDATA_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2SMIC_SSDATA_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x100; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2SMIC_SSDATA_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x200; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2SMIC_SSDATA_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x300; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2SMIC_SSDATA_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x400; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2SMIC_SSDATA_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x500; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2SMIC_SSDATA_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x600; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2SMIC_SSDATA_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700; \
	_pad_share_macro_read_value_ |= 0x700; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2SMIC_SSDATA_PORT_REN(v) { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x800; \
	_pad_share_macro_read_value_ |= (v&0x1)<<11; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMLP_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMLP_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x1000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMLP_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x2000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMLP_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x3000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMLP_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x4000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMLP_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x5000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMLP_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x6000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMLP_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000; \
	_pad_share_macro_read_value_ |= 0x7000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMLP_PORT_REN(v) { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x8000; \
	_pad_share_macro_read_value_ |= (v&0x1)<<15; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMLN_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMLN_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x10000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMLN_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x20000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMLN_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x30000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMLN_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x40000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMLN_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x50000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMLN_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x60000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMLN_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000; \
	_pad_share_macro_read_value_ |= 0x70000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMLN_PORT_REN(v) { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x80000; \
	_pad_share_macro_read_value_ |= (v&0x1)<<19; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMRP_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMRP_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x100000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMRP_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x200000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMRP_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x300000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMRP_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x400000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMRP_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x500000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMRP_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x600000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMRP_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x700000; \
	_pad_share_macro_read_value_ |= 0x700000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMRP_PORT_REN(v) { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x800000; \
	_pad_share_macro_read_value_ |= (v&0x1)<<23; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMRN_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMRN_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x1000000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMRN_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x2000000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMRN_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x3000000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMRN_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x4000000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMRN_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x5000000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMRN_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x6000000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMRN_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x7000000; \
	_pad_share_macro_read_value_ |= 0x7000000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_DOPWMRN_PORT_REN(v) { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x8000000; \
	_pad_share_macro_read_value_ |= (v&0x1)<<27; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2S2_MCLK_func0 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x0; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2S2_MCLK_func1 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x10000000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2S2_MCLK_func2 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x20000000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2S2_MCLK_func3 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x30000000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2S2_MCLK_func4 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x40000000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2S2_MCLK_func5 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x50000000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2S2_MCLK_func6 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x60000000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2S2_MCLK_func7 { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x70000000; \
	_pad_share_macro_read_value_ |= 0x70000000; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#define _SET_PAD_PAD_I2S2_MCLK_PORT_REN(v) { \
	uint32_t _pad_share_macro_read_value_=MA_INW(pad_share_ctrl_3_REG_ADDR); \
	_pad_share_macro_read_value_ &= ~0x80000000; \
	_pad_share_macro_read_value_ |= (v&0x1)<<31; \
	MA_OUTW(pad_share_ctrl_3_REG_ADDR,_pad_share_macro_read_value_); \
}

#endif //_PAD_SHARE_MACRO_H_
