/**********************************************************************
*
* rst_gen controller C MACRO generated by easy-chip
* generated in Wed, 25 Jul 2018 04:42:18 GMT
*
******************************************************************/

#ifndef _RST_GEN_MACRO_H_
#define _RST_GEN_MACRO_H_
#include "cdl_types.h"
#include "hw_maps.h"

//#define RST_GEN_BASE_ADDR 0x0
#define Software_RESET_assert0_REG_ADDR RST_GEN_BASE_ADDR + 0x0
#define Software_RESET_assert1_REG_ADDR RST_GEN_BASE_ADDR + 0x4

#define Software_RESET_status0_REG_ADDR RST_GEN_BASE_ADDR + 0x8
#define Software_RESET_status1_REG_ADDR RST_GEN_BASE_ADDR + 0xC

#define _READ_RESET_STATUS_sys_aresetn_116_(v) { \
	uint32_t _rst_gen_macro_read_sys_aresetn_116_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_sys_aresetn_116_status_ >> 0) & 0x1;\
}

#define _ASSERT_RESET_sys_aresetn_116_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_sys_aresetn_116_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_sys_aresetn_116_assert_ |= 0x1; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_sys_aresetn_116_assert_); \
	do { \
		_READ_RESET_STATUS_sys_aresetn_116_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_sys_aresetn_116_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_sys_aresetn_116_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_sys_aresetn_116_clear_ &= ~0x1; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_sys_aresetn_116_clear_); \
	do { \
		_READ_RESET_STATUS_sys_aresetn_116_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_sys_hresetn_116_(v) { \
	uint32_t _rst_gen_macro_read_sys_hresetn_116_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_sys_hresetn_116_status_ >> 1) & 0x1;\
}

#define _ASSERT_RESET_sys_hresetn_116_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_sys_hresetn_116_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_sys_hresetn_116_assert_ |= 0x2; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_sys_hresetn_116_assert_); \
	do { \
		_READ_RESET_STATUS_sys_hresetn_116_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_sys_hresetn_116_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_sys_hresetn_116_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_sys_hresetn_116_clear_ &= ~0x2; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_sys_hresetn_116_clear_); \
	do { \
		_READ_RESET_STATUS_sys_hresetn_116_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_sys_presetn_(v) { \
	uint32_t _rst_gen_macro_read_sys_presetn_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_sys_presetn_status_ >> 2) & 0x1;\
}

#define _ASSERT_RESET_sys_presetn_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_sys_presetn_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_sys_presetn_assert_ |= 0x4; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_sys_presetn_assert_); \
	do { \
		_READ_RESET_STATUS_sys_presetn_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_sys_presetn_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_sys_presetn_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_sys_presetn_clear_ &= ~0x4; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_sys_presetn_clear_); \
	do { \
		_READ_RESET_STATUS_sys_presetn_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_sys_aon_presetn_(v) { \
	uint32_t _rst_gen_macro_read_sys_aon_presetn_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_sys_aon_presetn_status_ >> 3) & 0x1;\
}

#define _ASSERT_RESET_sys_aon_presetn_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_sys_aon_presetn_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_sys_aon_presetn_assert_ |= 0x8; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_sys_aon_presetn_assert_); \
	do { \
		_READ_RESET_STATUS_sys_aon_presetn_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_sys_aon_presetn_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_sys_aon_presetn_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_sys_aon_presetn_clear_ &= ~0x8; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_sys_aon_presetn_clear_); \
	do { \
		_READ_RESET_STATUS_sys_aon_presetn_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_dsp0_BReset_295_(v) { \
	uint32_t _rst_gen_macro_read_dsp0_BReset_295_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_dsp0_BReset_295_status_ >> 4) & 0x1;\
}

#define _ASSERT_RESET_dsp0_BReset_295_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_dsp0_BReset_295_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_dsp0_BReset_295_assert_ |= 0x10; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_dsp0_BReset_295_assert_); \
	do { \
		_READ_RESET_STATUS_dsp0_BReset_295_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _CLEAR_RESET_dsp0_BReset_295_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_dsp0_BReset_295_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_dsp0_BReset_295_clear_ &= ~0x10; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_dsp0_BReset_295_clear_); \
	do { \
		_READ_RESET_STATUS_dsp0_BReset_295_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _READ_RESET_STATUS_dsp0_Dreset_295_(v) { \
	uint32_t _rst_gen_macro_read_dsp0_Dreset_295_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_dsp0_Dreset_295_status_ >> 5) & 0x1;\
}

#define _ASSERT_RESET_dsp0_Dreset_295_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_dsp0_Dreset_295_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_dsp0_Dreset_295_assert_ |= 0x20; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_dsp0_Dreset_295_assert_); \
	do { \
		_READ_RESET_STATUS_dsp0_Dreset_295_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _CLEAR_RESET_dsp0_Dreset_295_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_dsp0_Dreset_295_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_dsp0_Dreset_295_clear_ &= ~0x20; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_dsp0_Dreset_295_clear_); \
	do { \
		_READ_RESET_STATUS_dsp0_Dreset_295_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _READ_RESET_STATUS_dsp1_BReset_296_(v) { \
	uint32_t _rst_gen_macro_read_dsp1_BReset_296_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_dsp1_BReset_296_status_ >> 6) & 0x1;\
}

#define _ASSERT_RESET_dsp1_BReset_296_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_dsp1_BReset_296_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_dsp1_BReset_296_assert_ |= 0x40; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_dsp1_BReset_296_assert_); \
	do { \
		_READ_RESET_STATUS_dsp1_BReset_296_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _CLEAR_RESET_dsp1_BReset_296_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_dsp1_BReset_296_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_dsp1_BReset_296_clear_ &= ~0x40; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_dsp1_BReset_296_clear_); \
	do { \
		_READ_RESET_STATUS_dsp1_BReset_296_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _READ_RESET_STATUS_dsp1_Dreset_296_(v) { \
	uint32_t _rst_gen_macro_read_dsp1_Dreset_296_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_dsp1_Dreset_296_status_ >> 7) & 0x1;\
}

#define _ASSERT_RESET_dsp1_Dreset_296_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_dsp1_Dreset_296_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_dsp1_Dreset_296_assert_ |= 0x80; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_dsp1_Dreset_296_assert_); \
	do { \
		_READ_RESET_STATUS_dsp1_Dreset_296_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _CLEAR_RESET_dsp1_Dreset_296_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_dsp1_Dreset_296_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_dsp1_Dreset_296_clear_ &= ~0x80; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_dsp1_Dreset_296_clear_); \
	do { \
		_READ_RESET_STATUS_dsp1_Dreset_296_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _READ_RESET_STATUS_dmac_core_resetn_115_(v) { \
	uint32_t _rst_gen_macro_read_dmac_core_resetn_115_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_dmac_core_resetn_115_status_ >> 8) & 0x1;\
}

#define _ASSERT_RESET_dmac_core_resetn_115_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_dmac_core_resetn_115_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_dmac_core_resetn_115_assert_ |= 0x100; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_dmac_core_resetn_115_assert_); \
	do { \
		_READ_RESET_STATUS_dmac_core_resetn_115_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_dmac_core_resetn_115_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_dmac_core_resetn_115_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_dmac_core_resetn_115_clear_ &= ~0x100; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_dmac_core_resetn_115_clear_); \
	do { \
		_READ_RESET_STATUS_dmac_core_resetn_115_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_dmac_hresetn_115_(v) { \
	uint32_t _rst_gen_macro_read_dmac_hresetn_115_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_dmac_hresetn_115_status_ >> 9) & 0x1;\
}

#define _ASSERT_RESET_dmac_hresetn_115_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_dmac_hresetn_115_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_dmac_hresetn_115_assert_ |= 0x200; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_dmac_hresetn_115_assert_); \
	do { \
		_READ_RESET_STATUS_dmac_hresetn_115_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_dmac_hresetn_115_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_dmac_hresetn_115_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_dmac_hresetn_115_clear_ &= ~0x200; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_dmac_hresetn_115_clear_); \
	do { \
		_READ_RESET_STATUS_dmac_hresetn_115_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_gpio_PRESETn_140_(v) { \
	uint32_t _rst_gen_macro_read_gpio_PRESETn_140_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_gpio_PRESETn_140_status_ >> 10) & 0x1;\
}

#define _ASSERT_RESET_gpio_PRESETn_140_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_gpio_PRESETn_140_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_gpio_PRESETn_140_assert_ |= 0x400; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_gpio_PRESETn_140_assert_); \
	do { \
		_READ_RESET_STATUS_gpio_PRESETn_140_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_gpio_PRESETn_140_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_gpio_PRESETn_140_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_gpio_PRESETn_140_clear_ &= ~0x400; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_gpio_PRESETn_140_clear_); \
	do { \
		_READ_RESET_STATUS_gpio_PRESETn_140_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_i2cs_ic_rst_n_131_(v) { \
	uint32_t _rst_gen_macro_read_i2cs_ic_rst_n_131_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_i2cs_ic_rst_n_131_status_ >> 11) & 0x1;\
}

#define _ASSERT_RESET_i2cs_ic_rst_n_131_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_i2cs_ic_rst_n_131_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_i2cs_ic_rst_n_131_assert_ |= 0x800; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_i2cs_ic_rst_n_131_assert_); \
	do { \
		_READ_RESET_STATUS_i2cs_ic_rst_n_131_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_i2cs_ic_rst_n_131_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_i2cs_ic_rst_n_131_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_i2cs_ic_rst_n_131_clear_ &= ~0x800; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_i2cs_ic_rst_n_131_clear_); \
	do { \
		_READ_RESET_STATUS_i2cs_ic_rst_n_131_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_i2cs_presetn_131_(v) { \
	uint32_t _rst_gen_macro_read_i2cs_presetn_131_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_i2cs_presetn_131_status_ >> 12) & 0x1;\
}

#define _ASSERT_RESET_i2cs_presetn_131_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_i2cs_presetn_131_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_i2cs_presetn_131_assert_ |= 0x1000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_i2cs_presetn_131_assert_); \
	do { \
		_READ_RESET_STATUS_i2cs_presetn_131_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_i2cs_presetn_131_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_i2cs_presetn_131_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_i2cs_presetn_131_clear_ &= ~0x1000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_i2cs_presetn_131_clear_); \
	do { \
		_READ_RESET_STATUS_i2cs_presetn_131_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_i2cm_ic_rst_n_132_(v) { \
	uint32_t _rst_gen_macro_read_i2cm_ic_rst_n_132_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_i2cm_ic_rst_n_132_status_ >> 13) & 0x1;\
}

#define _ASSERT_RESET_i2cm_ic_rst_n_132_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_i2cm_ic_rst_n_132_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_i2cm_ic_rst_n_132_assert_ |= 0x2000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_i2cm_ic_rst_n_132_assert_); \
	do { \
		_READ_RESET_STATUS_i2cm_ic_rst_n_132_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_i2cm_ic_rst_n_132_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_i2cm_ic_rst_n_132_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_i2cm_ic_rst_n_132_clear_ &= ~0x2000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_i2cm_ic_rst_n_132_clear_); \
	do { \
		_READ_RESET_STATUS_i2cm_ic_rst_n_132_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_i2cm_presetn_132_(v) { \
	uint32_t _rst_gen_macro_read_i2cm_presetn_132_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_i2cm_presetn_132_status_ >> 14) & 0x1;\
}

#define _ASSERT_RESET_i2cm_presetn_132_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_i2cm_presetn_132_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_i2cm_presetn_132_assert_ |= 0x4000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_i2cm_presetn_132_assert_); \
	do { \
		_READ_RESET_STATUS_i2cm_presetn_132_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_i2cm_presetn_132_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_i2cm_presetn_132_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_i2cm_presetn_132_clear_ &= ~0x4000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_i2cm_presetn_132_clear_); \
	do { \
		_READ_RESET_STATUS_i2cm_presetn_132_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_SPI_BnRES_130_(v) { \
	uint32_t _rst_gen_macro_read_SPI_BnRES_130_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_SPI_BnRES_130_status_ >> 15) & 0x1;\
}

#define _ASSERT_RESET_SPI_BnRES_130_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_SPI_BnRES_130_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_SPI_BnRES_130_assert_ |= 0x8000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_SPI_BnRES_130_assert_); \
	do { \
		_READ_RESET_STATUS_SPI_BnRES_130_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_SPI_BnRES_130_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_SPI_BnRES_130_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_SPI_BnRES_130_clear_ &= ~0x8000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_SPI_BnRES_130_clear_); \
	do { \
		_READ_RESET_STATUS_SPI_BnRES_130_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_SPI_nSSRST_130_(v) { \
	uint32_t _rst_gen_macro_read_SPI_nSSRST_130_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_SPI_nSSRST_130_status_ >> 16) & 0x1;\
}

#define _ASSERT_RESET_SPI_nSSRST_130_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_SPI_nSSRST_130_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_SPI_nSSRST_130_assert_ |= 0x10000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_SPI_nSSRST_130_assert_); \
	do { \
		_READ_RESET_STATUS_SPI_nSSRST_130_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_SPI_nSSRST_130_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_SPI_nSSRST_130_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_SPI_nSSRST_130_clear_ &= ~0x10000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_SPI_nSSRST_130_clear_); \
	do { \
		_READ_RESET_STATUS_SPI_nSSRST_130_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_timer_PRESETn_141_(v) { \
	uint32_t _rst_gen_macro_read_timer_PRESETn_141_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_timer_PRESETn_141_status_ >> 17) & 0x1;\
}

#define _ASSERT_RESET_timer_PRESETn_141_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_timer_PRESETn_141_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_timer_PRESETn_141_assert_ |= 0x20000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_timer_PRESETn_141_assert_); \
	do { \
		_READ_RESET_STATUS_timer_PRESETn_141_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_timer_PRESETn_141_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_timer_PRESETn_141_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_timer_PRESETn_141_clear_ &= ~0x20000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_timer_PRESETn_141_clear_); \
	do { \
		_READ_RESET_STATUS_timer_PRESETn_141_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_uart0_presetn_136_(v) { \
	uint32_t _rst_gen_macro_read_uart0_presetn_136_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_uart0_presetn_136_status_ >> 18) & 0x1;\
}

#define _ASSERT_RESET_uart0_presetn_136_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_uart0_presetn_136_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_uart0_presetn_136_assert_ |= 0x40000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_uart0_presetn_136_assert_); \
	do { \
		_READ_RESET_STATUS_uart0_presetn_136_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_uart0_presetn_136_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_uart0_presetn_136_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_uart0_presetn_136_clear_ &= ~0x40000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_uart0_presetn_136_clear_); \
	do { \
		_READ_RESET_STATUS_uart0_presetn_136_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_uart0_s_rst_n_136_(v) { \
	uint32_t _rst_gen_macro_read_uart0_s_rst_n_136_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_uart0_s_rst_n_136_status_ >> 19) & 0x1;\
}

#define _ASSERT_RESET_uart0_s_rst_n_136_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_uart0_s_rst_n_136_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_uart0_s_rst_n_136_assert_ |= 0x80000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_uart0_s_rst_n_136_assert_); \
	do { \
		_READ_RESET_STATUS_uart0_s_rst_n_136_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_uart0_s_rst_n_136_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_uart0_s_rst_n_136_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_uart0_s_rst_n_136_clear_ &= ~0x80000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_uart0_s_rst_n_136_clear_); \
	do { \
		_READ_RESET_STATUS_uart0_s_rst_n_136_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_uart1_presetn_137_(v) { \
	uint32_t _rst_gen_macro_read_uart1_presetn_137_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_uart1_presetn_137_status_ >> 20) & 0x1;\
}

#define _ASSERT_RESET_uart1_presetn_137_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_uart1_presetn_137_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_uart1_presetn_137_assert_ |= 0x100000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_uart1_presetn_137_assert_); \
	do { \
		_READ_RESET_STATUS_uart1_presetn_137_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_uart1_presetn_137_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_uart1_presetn_137_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_uart1_presetn_137_clear_ &= ~0x100000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_uart1_presetn_137_clear_); \
	do { \
		_READ_RESET_STATUS_uart1_presetn_137_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_uart1_s_rst_n_137_(v) { \
	uint32_t _rst_gen_macro_read_uart1_s_rst_n_137_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_uart1_s_rst_n_137_status_ >> 21) & 0x1;\
}

#define _ASSERT_RESET_uart1_s_rst_n_137_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_uart1_s_rst_n_137_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_uart1_s_rst_n_137_assert_ |= 0x200000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_uart1_s_rst_n_137_assert_); \
	do { \
		_READ_RESET_STATUS_uart1_s_rst_n_137_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_uart1_s_rst_n_137_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_uart1_s_rst_n_137_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_uart1_s_rst_n_137_clear_ &= ~0x200000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_uart1_s_rst_n_137_clear_); \
	do { \
		_READ_RESET_STATUS_uart1_s_rst_n_137_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_USB_NRST_161_(v) { \
	uint32_t _rst_gen_macro_read_USB_NRST_161_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_USB_NRST_161_status_ >> 22) & 0x1;\
}

#define _ASSERT_RESET_USB_NRST_161_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_USB_NRST_161_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_USB_NRST_161_assert_ |= 0x400000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_USB_NRST_161_assert_); \
	do { \
		_READ_RESET_STATUS_USB_NRST_161_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_USB_NRST_161_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_USB_NRST_161_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_USB_NRST_161_clear_ &= ~0x400000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_USB_NRST_161_clear_); \
	do { \
		_READ_RESET_STATUS_USB_NRST_161_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_i2sadc_presetn_126_(v) { \
	uint32_t _rst_gen_macro_read_i2sadc_presetn_126_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_i2sadc_presetn_126_status_ >> 23) & 0x1;\
}

#define _ASSERT_RESET_i2sadc_presetn_126_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_i2sadc_presetn_126_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_i2sadc_presetn_126_assert_ |= 0x800000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_i2sadc_presetn_126_assert_); \
	do { \
		_READ_RESET_STATUS_i2sadc_presetn_126_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_i2sadc_presetn_126_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_i2sadc_presetn_126_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_i2sadc_presetn_126_clear_ &= ~0x800000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_i2sadc_presetn_126_clear_); \
	do { \
		_READ_RESET_STATUS_i2sadc_presetn_126_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_i2sadc_sresetn_126_(v) { \
	uint32_t _rst_gen_macro_read_i2sadc_sresetn_126_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_i2sadc_sresetn_126_status_ >> 24) & 0x1;\
}

#define _ASSERT_RESET_i2sadc_sresetn_126_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_i2sadc_sresetn_126_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_i2sadc_sresetn_126_assert_ |= 0x1000000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_i2sadc_sresetn_126_assert_); \
	do { \
		_READ_RESET_STATUS_i2sadc_sresetn_126_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_i2sadc_sresetn_126_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_i2sadc_sresetn_126_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_i2sadc_sresetn_126_clear_ &= ~0x1000000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_i2sadc_sresetn_126_clear_); \
	do { \
		_READ_RESET_STATUS_i2sadc_sresetn_126_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_i2sdac_presetn_127_(v) { \
	uint32_t _rst_gen_macro_read_i2sdac_presetn_127_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_i2sdac_presetn_127_status_ >> 25) & 0x1;\
}

#define _ASSERT_RESET_i2sdac_presetn_127_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_i2sdac_presetn_127_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_i2sdac_presetn_127_assert_ |= 0x2000000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_i2sdac_presetn_127_assert_); \
	do { \
		_READ_RESET_STATUS_i2sdac_presetn_127_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_i2sdac_presetn_127_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_i2sdac_presetn_127_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_i2sdac_presetn_127_clear_ &= ~0x2000000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_i2sdac_presetn_127_clear_); \
	do { \
		_READ_RESET_STATUS_i2sdac_presetn_127_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_i2sdac_sresetn_127_(v) { \
	uint32_t _rst_gen_macro_read_i2sdac_sresetn_127_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_i2sdac_sresetn_127_status_ >> 26) & 0x1;\
}

#define _ASSERT_RESET_i2sdac_sresetn_127_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_i2sdac_sresetn_127_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_i2sdac_sresetn_127_assert_ |= 0x4000000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_i2sdac_sresetn_127_assert_); \
	do { \
		_READ_RESET_STATUS_i2sdac_sresetn_127_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_i2sdac_sresetn_127_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_i2sdac_sresetn_127_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_i2sdac_sresetn_127_clear_ &= ~0x4000000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_i2sdac_sresetn_127_clear_); \
	do { \
		_READ_RESET_STATUS_i2sdac_sresetn_127_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_i2s1_presetn_128_(v) { \
	uint32_t _rst_gen_macro_read_i2s1_presetn_128_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_i2s1_presetn_128_status_ >> 27) & 0x1;\
}

#define _ASSERT_RESET_i2s1_presetn_128_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_i2s1_presetn_128_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_i2s1_presetn_128_assert_ |= 0x8000000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_i2s1_presetn_128_assert_); \
	do { \
		_READ_RESET_STATUS_i2s1_presetn_128_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_i2s1_presetn_128_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_i2s1_presetn_128_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_i2s1_presetn_128_clear_ &= ~0x8000000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_i2s1_presetn_128_clear_); \
	do { \
		_READ_RESET_STATUS_i2s1_presetn_128_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_i2s1_sresetn_128_(v) { \
	uint32_t _rst_gen_macro_read_i2s1_sresetn_128_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_i2s1_sresetn_128_status_ >> 28) & 0x1;\
}

#define _ASSERT_RESET_i2s1_sresetn_128_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_i2s1_sresetn_128_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_i2s1_sresetn_128_assert_ |= 0x10000000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_i2s1_sresetn_128_assert_); \
	do { \
		_READ_RESET_STATUS_i2s1_sresetn_128_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_i2s1_sresetn_128_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_i2s1_sresetn_128_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_i2s1_sresetn_128_clear_ &= ~0x10000000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_i2s1_sresetn_128_clear_); \
	do { \
		_READ_RESET_STATUS_i2s1_sresetn_128_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_i2svad_presetn_129_(v) { \
	uint32_t _rst_gen_macro_read_i2svad_presetn_129_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_i2svad_presetn_129_status_ >> 29) & 0x1;\
}

#define _ASSERT_RESET_i2svad_presetn_129_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_i2svad_presetn_129_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_i2svad_presetn_129_assert_ |= 0x20000000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_i2svad_presetn_129_assert_); \
	do { \
		_READ_RESET_STATUS_i2svad_presetn_129_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_i2svad_presetn_129_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_i2svad_presetn_129_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_i2svad_presetn_129_clear_ &= ~0x20000000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_i2svad_presetn_129_clear_); \
	do { \
		_READ_RESET_STATUS_i2svad_presetn_129_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_i2svad_sresetn_129_(v) { \
	uint32_t _rst_gen_macro_read_i2svad_sresetn_129_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_i2svad_sresetn_129_status_ >> 30) & 0x1;\
}

#define _ASSERT_RESET_i2svad_sresetn_129_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_i2svad_sresetn_129_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_i2svad_sresetn_129_assert_ |= 0x40000000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_i2svad_sresetn_129_assert_); \
	do { \
		_READ_RESET_STATUS_i2svad_sresetn_129_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_i2svad_sresetn_129_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_i2svad_sresetn_129_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_i2svad_sresetn_129_clear_ &= ~0x40000000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_i2svad_sresetn_129_clear_); \
	do { \
		_READ_RESET_STATUS_i2svad_sresetn_129_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_acdcucp_presetn_292_(v) { \
	uint32_t _rst_gen_macro_read_acdcucp_presetn_292_status_=MA_INW(Software_RESET_status0_REG_ADDR); \
	v = (_rst_gen_macro_read_acdcucp_presetn_292_status_ >> 31) & 0x1;\
}

#define _ASSERT_RESET_acdcucp_presetn_292_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_acdcucp_presetn_292_assert_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_acdcucp_presetn_292_assert_ |= 0x80000000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_acdcucp_presetn_292_assert_); \
	do { \
		_READ_RESET_STATUS_acdcucp_presetn_292_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_acdcucp_presetn_292_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_acdcucp_presetn_292_clear_=MA_INW(Software_RESET_assert0_REG_ADDR); \
	_rst_gen_macro_read_acdcucp_presetn_292_clear_ &= ~0x80000000; \
	MA_OUTW(Software_RESET_assert0_REG_ADDR,_rst_gen_macro_read_acdcucp_presetn_292_clear_); \
	do { \
		_READ_RESET_STATUS_acdcucp_presetn_292_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_wdt_PRESETn_139_(v) { \
	uint32_t _rst_gen_macro_read_wdt_PRESETn_139_status_=MA_INW(Software_RESET_status1_REG_ADDR); \
	v = (_rst_gen_macro_read_wdt_PRESETn_139_status_ >> 0) & 0x1;\
}

#define _ASSERT_RESET_wdt_PRESETn_139_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_wdt_PRESETn_139_assert_=MA_INW(Software_RESET_assert1_REG_ADDR); \
	_rst_gen_macro_read_wdt_PRESETn_139_assert_ |= 0x1; \
	MA_OUTW(Software_RESET_assert1_REG_ADDR,_rst_gen_macro_read_wdt_PRESETn_139_assert_); \
	do { \
		_READ_RESET_STATUS_wdt_PRESETn_139_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_wdt_PRESETn_139_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_wdt_PRESETn_139_clear_=MA_INW(Software_RESET_assert1_REG_ADDR); \
	_rst_gen_macro_read_wdt_PRESETn_139_clear_ &= ~0x1; \
	MA_OUTW(Software_RESET_assert1_REG_ADDR,_rst_gen_macro_read_wdt_PRESETn_139_clear_); \
	do { \
		_READ_RESET_STATUS_wdt_PRESETn_139_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_wdt_WDOGRESn_139_(v) { \
	uint32_t _rst_gen_macro_read_wdt_WDOGRESn_139_status_=MA_INW(Software_RESET_status1_REG_ADDR); \
	v = (_rst_gen_macro_read_wdt_WDOGRESn_139_status_ >> 1) & 0x1;\
}

#define _ASSERT_RESET_wdt_WDOGRESn_139_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_wdt_WDOGRESn_139_assert_=MA_INW(Software_RESET_assert1_REG_ADDR); \
	_rst_gen_macro_read_wdt_WDOGRESn_139_assert_ |= 0x2; \
	MA_OUTW(Software_RESET_assert1_REG_ADDR,_rst_gen_macro_read_wdt_WDOGRESn_139_assert_); \
	do { \
		_READ_RESET_STATUS_wdt_WDOGRESn_139_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_wdt_WDOGRESn_139_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_wdt_WDOGRESn_139_clear_=MA_INW(Software_RESET_assert1_REG_ADDR); \
	_rst_gen_macro_read_wdt_WDOGRESn_139_clear_ &= ~0x2; \
	MA_OUTW(Software_RESET_assert1_REG_ADDR,_rst_gen_macro_read_wdt_WDOGRESn_139_clear_); \
	do { \
		_READ_RESET_STATUS_wdt_WDOGRESn_139_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_NRST_347_(v) { \
	uint32_t _rst_gen_macro_read_NRST_347_status_=MA_INW(Software_RESET_status1_REG_ADDR); \
	v = (_rst_gen_macro_read_NRST_347_status_ >> 2) & 0x1;\
}

#define _ASSERT_RESET_NRST_347_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_NRST_347_assert_=MA_INW(Software_RESET_assert1_REG_ADDR); \
	_rst_gen_macro_read_NRST_347_assert_ |= 0x4; \
	MA_OUTW(Software_RESET_assert1_REG_ADDR,_rst_gen_macro_read_NRST_347_assert_); \
	do { \
		_READ_RESET_STATUS_NRST_347_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_NRST_347_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_NRST_347_clear_=MA_INW(Software_RESET_assert1_REG_ADDR); \
	_rst_gen_macro_read_NRST_347_clear_ &= ~0x4; \
	MA_OUTW(Software_RESET_assert1_REG_ADDR,_rst_gen_macro_read_NRST_347_clear_); \
	do { \
		_READ_RESET_STATUS_NRST_347_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#define _READ_RESET_STATUS_ptc_presetn_138_(v) { \
	uint32_t _rst_gen_macro_read_ptc_presetn_138_status_=MA_INW(Software_RESET_status1_REG_ADDR); \
	v = (_rst_gen_macro_read_ptc_presetn_138_status_ >> 3) & 0x1;\
}

#define _ASSERT_RESET_ptc_presetn_138_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_ptc_presetn_138_assert_=MA_INW(Software_RESET_assert1_REG_ADDR); \
	_rst_gen_macro_read_ptc_presetn_138_assert_ |= 0x8; \
	MA_OUTW(Software_RESET_assert1_REG_ADDR,_rst_gen_macro_read_ptc_presetn_138_assert_); \
	do { \
		_READ_RESET_STATUS_ptc_presetn_138_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=0); \
}

#define _CLEAR_RESET_ptc_presetn_138_ { \
	int _read_reset_signal_status_; \
	uint32_t _rst_gen_macro_read_ptc_presetn_138_clear_=MA_INW(Software_RESET_assert1_REG_ADDR); \
	_rst_gen_macro_read_ptc_presetn_138_clear_ &= ~0x8; \
	MA_OUTW(Software_RESET_assert1_REG_ADDR,_rst_gen_macro_read_ptc_presetn_138_clear_); \
	do { \
		_READ_RESET_STATUS_ptc_presetn_138_(_read_reset_signal_status_); \
	} while(_read_reset_signal_status_!=1); \
}

#endif //_RST_GEN_MACRO_H_
