/**********************************************************************
*
* sys_con C MACRO generated by easy-chip
* generated in Wed, 25 Jul 2018 04:42:19 GMT
*
******************************************************************/

#ifndef _SYS_CON_MACRO_H_
#define _SYS_CON_MACRO_H_
#include "cdl_types.h"
#include "hw_maps.h"

#define dsp0resetvec_REG_ADDR SYS_CON_BASE_ADDR + 0x0
#define dsp0faultinfo_REG_ADDR SYS_CON_BASE_ADDR + 0x4
#define dsp0config_REG_ADDR SYS_CON_BASE_ADDR + 0x8
#define dsp0debug_REG_ADDR SYS_CON_BASE_ADDR + 0xc
#define dsp1resetvec_REG_ADDR SYS_CON_BASE_ADDR + 0x10
#define dsp1faultinfo_REG_ADDR SYS_CON_BASE_ADDR + 0x14
#define dsp1config_REG_ADDR SYS_CON_BASE_ADDR + 0x18
#define dsp1debug_REG_ADDR SYS_CON_BASE_ADDR + 0x1c
#define interrupt_pol_REG_ADDR SYS_CON_BASE_ADDR + 0x20
#define usb_config_REG_ADDR SYS_CON_BASE_ADDR + 0x24
#define usb_debug_REG_ADDR SYS_CON_BASE_ADDR + 0x28
#define i2s0_control_REG_ADDR SYS_CON_BASE_ADDR + 0x2c
#define cdc_control_REG_ADDR SYS_CON_BASE_ADDR + 0x30
#define pll1_config_REG_ADDR SYS_CON_BASE_ADDR + 0x34
#define pll2_config_REG_ADDR SYS_CON_BASE_ADDR + 0x38
#define pll3_config_REG_ADDR SYS_CON_BASE_ADDR + 0x3c
#define pmu_REG_ADDR SYS_CON_BASE_ADDR + 0x40
#define interrupt_control_REG_ADDR SYS_CON_BASE_ADDR + 0x44
#define boot_strap_REG_ADDR SYS_CON_BASE_ADDR + 0x48
#define dma_req_control_REG_ADDR SYS_CON_BASE_ADDR + 0x4c
#define debug_register_REG_ADDR SYS_CON_BASE_ADDR + 0x50
#define osc_pad_control_REG_ADDR SYS_CON_BASE_ADDR + 0x54
#define i2s1_control_REG_ADDR SYS_CON_BASE_ADDR + 0x58
#define i2s1_delay_control_REG_ADDR SYS_CON_BASE_ADDR + 0x5c
#define dsp0_mem_delay_REG_ADDR SYS_CON_BASE_ADDR + 0x60
#define dsp1_mem_delay_REG_ADDR SYS_CON_BASE_ADDR + 0x64
#define power_up_delay_control_REG_ADDR SYS_CON_BASE_ADDR + 0x68
#define power_down_delay_control_REG_ADDR SYS_CON_BASE_ADDR + 0x6c
#define info_register_REG_ADDR SYS_CON_BASE_ADDR + 0x70
#define vad_register_REG_ADDR SYS_CON_BASE_ADDR + 0x74

#define _SET_SYSCON_REG_dsp0resetvec_AltResetVec_295(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0resetvec_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0xFFFFFFFF; \
	_sys_con_macro_read_value_ |= (v&0xFFFFFFFF)<<0; \
	MA_OUTW(dsp0resetvec_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp0resetvec_AltResetVec_295(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0resetvec_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>0)&0xFFFFFFFF; \
}

#define _SET_SYSCON_REG_dsp0config_RunStall_295(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x1; \
	_sys_con_macro_read_value_ |= (v&0x1)<<0; \
	MA_OUTW(dsp0config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp0config_RunStall_295(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>0)&0x1; \
}

#define _SET_SYSCON_REG_dsp0config_StatVectorSel_310(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x2; \
	_sys_con_macro_read_value_ |= (v&0x1)<<1; \
	MA_OUTW(dsp0config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp0config_StatVectorSel_310(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>1)&0x1; \
}

#define _SET_SYSCON_REG_dsp0config_TrigIn_iDMA_295(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x4; \
	_sys_con_macro_read_value_ |= (v&0x1)<<2; \
	MA_OUTW(dsp0config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp0config_TrigIn_iDMA_295(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>2)&0x1; \
}

#define _SET_SYSCON_REG_dsp0config_BreakIn_344(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x8; \
	_sys_con_macro_read_value_ |= (v&0x1)<<3; \
	MA_OUTW(dsp0config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp0config_BreakIn_344(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>3)&0x1; \
}

#define _SET_SYSCON_REG_dsp0config_BreakOutAck_344(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x10; \
	_sys_con_macro_read_value_ |= (v&0x1)<<4; \
	MA_OUTW(dsp0config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp0config_BreakOutAck_344(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>4)&0x1; \
}

#define _SET_SYSCON_REG_dsp0config_OCDHaltOnReset_295(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x20; \
	_sys_con_macro_read_value_ |= (v&0x1)<<5; \
	MA_OUTW(dsp0config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp0config_OCDHaltOnReset_295(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>5)&0x1; \
}

#define _SET_SYSCON_REG_dsp0config_dsp0_en_344(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x40; \
	_sys_con_macro_read_value_ |= (v&0x1)<<6; \
	MA_OUTW(dsp0config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp0config_dsp0_en_344(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>6)&0x1; \
}

#define _SET_SYSCON_REG_dsp0config_PRID_295(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0xFFFF0000; \
	_sys_con_macro_read_value_ |= (v&0xFFFF)<<16; \
	MA_OUTW(dsp0config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp0config_PRID_295(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>16)&0xFFFF; \
}

#define _SET_SYSCON_REG_dsp1resetvec_AltResetVec_296(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1resetvec_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0xFFFFFFFF; \
	_sys_con_macro_read_value_ |= (v&0xFFFFFFFF)<<0; \
	MA_OUTW(dsp1resetvec_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp1resetvec_AltResetVec_296(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1resetvec_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>0)&0xFFFFFFFF; \
}

#define _SET_SYSCON_REG_dsp1config_RunStall_296(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x1; \
	_sys_con_macro_read_value_ |= (v&0x1)<<0; \
	MA_OUTW(dsp1config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp1config_RunStall_296(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>0)&0x1; \
}

#define _SET_SYSCON_REG_dsp1config_StatVectorSel_296(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x2; \
	_sys_con_macro_read_value_ |= (v&0x1)<<1; \
	MA_OUTW(dsp1config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp1config_StatVectorSel_296(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>1)&0x1; \
}

#define _SET_SYSCON_REG_dsp1config_TrigIn_iDMA_296(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x4; \
	_sys_con_macro_read_value_ |= (v&0x1)<<2; \
	MA_OUTW(dsp1config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp1config_TrigIn_iDMA_296(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>2)&0x1; \
}

#define _SET_SYSCON_REG_dsp1config_BreakIn_344(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x8; \
	_sys_con_macro_read_value_ |= (v&0x1)<<3; \
	MA_OUTW(dsp1config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp1config_BreakIn_344(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>3)&0x1; \
}

#define _SET_SYSCON_REG_dsp1config_BreakOutAck_344(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x10; \
	_sys_con_macro_read_value_ |= (v&0x1)<<4; \
	MA_OUTW(dsp1config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp1config_BreakOutAck_344(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>4)&0x1; \
}

#define _SET_SYSCON_REG_dsp1config_OCDHaltOnReset_296(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x20; \
	_sys_con_macro_read_value_ |= (v&0x1)<<5; \
	MA_OUTW(dsp1config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp1config_OCDHaltOnReset_296(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>5)&0x1; \
}

#define _SET_SYSCON_REG_dsp1config_dsp1_en_344(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x40; \
	_sys_con_macro_read_value_ |= (v&0x1)<<6; \
	MA_OUTW(dsp1config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp1config_dsp1_en_344(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>6)&0x1; \
}

#define _SET_SYSCON_REG_dsp1config_PRID_296(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0xFFFF0000; \
	_sys_con_macro_read_value_ |= (v&0xFFFF)<<16; \
	MA_OUTW(dsp1config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp1config_PRID_296(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>16)&0xFFFF; \
}

#define _SET_SYSCON_REG_interrupt_pol_interrupt_pol_227(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(interrupt_pol_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0xFFFFFFFF; \
	_sys_con_macro_read_value_ |= (v&0xFFFFFFFF)<<0; \
	MA_OUTW(interrupt_pol_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_interrupt_pol_interrupt_pol_227(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(interrupt_pol_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>0)&0xFFFFFFFF; \
}

#define _SET_SYSCON_REG_usb_config_VBUSVAL_161(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(usb_config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x1; \
	_sys_con_macro_read_value_ |= (v&0x1)<<0; \
	MA_OUTW(usb_config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_usb_config_VBUSVAL_161(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(usb_config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>0)&0x1; \
}

#define _SET_SYSCON_REG_usb_config_VBUSSES_161(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(usb_config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x2; \
	_sys_con_macro_read_value_ |= (v&0x1)<<1; \
	MA_OUTW(usb_config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_usb_config_VBUSSES_161(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(usb_config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>1)&0x1; \
}

#define _SET_SYSCON_REG_usb_config_VBUSLO_161(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(usb_config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x4; \
	_sys_con_macro_read_value_ |= (v&0x1)<<2; \
	MA_OUTW(usb_config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_usb_config_VBUSLO_161(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(usb_config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>2)&0x1; \
}

#define _SET_SYSCON_REG_usb_config_CID_161(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(usb_config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x8; \
	_sys_con_macro_read_value_ |= (v&0x1)<<3; \
	MA_OUTW(usb_config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_usb_config_CID_161(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(usb_config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>3)&0x1; \
}

#define _SET_SYSCON_REG_usb_config_TM1_161(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(usb_config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x10; \
	_sys_con_macro_read_value_ |= (v&0x1)<<4; \
	MA_OUTW(usb_config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_usb_config_TM1_161(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(usb_config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>4)&0x1; \
}

#define _SET_SYSCON_REG_i2s0_control_i2s0_mode_345(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(i2s0_control_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x1; \
	_sys_con_macro_read_value_ |= (v&0x1)<<0; \
	MA_OUTW(i2s0_control_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_i2s0_control_i2s0_mode_345(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(i2s0_control_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>0)&0x1; \
}

#define _SET_SYSCON_REG_i2s0_control_i2s0_enable_345(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(i2s0_control_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x2; \
	_sys_con_macro_read_value_ |= (v&0x1)<<1; \
	MA_OUTW(i2s0_control_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_i2s0_control_i2s0_enable_345(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(i2s0_control_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>1)&0x1; \
}

#define _SET_SYSCON_REG_cdc_control_SI2C_347(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(cdc_control_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x80; \
	_sys_con_macro_read_value_ |= (v&0x1)<<7; \
	MA_OUTW(cdc_control_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_cdc_control_SI2C_347(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(cdc_control_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>7)&0x1; \
}

#define _SET_SYSCON_REG_cdc_control_adc_drvp_mntn_sel_288(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(cdc_control_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x100; \
	_sys_con_macro_read_value_ |= (v&0x1)<<8; \
	MA_OUTW(cdc_control_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_cdc_control_adc_drvp_mntn_sel_288(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(cdc_control_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>8)&0x1; \
}

#define _SET_SYSCON_REG_cdc_control_acdc_dac_data_sel_288(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(cdc_control_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x200; \
	_sys_con_macro_read_value_ |= (v&0x1)<<9; \
	MA_OUTW(cdc_control_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_cdc_control_acdc_dac_data_sel_288(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(cdc_control_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>9)&0x1; \
}

#define _SET_SYSCON_REG_cdc_control_acdc_dac_clk_sel_288(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(cdc_control_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x400; \
	_sys_con_macro_read_value_ |= (v&0x1)<<10; \
	MA_OUTW(cdc_control_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_cdc_control_acdc_dac_clk_sel_288(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(cdc_control_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>10)&0x1; \
}

#define _SET_SYSCON_REG_cdc_control_NLR_BYPASS_347(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(cdc_control_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x800; \
	_sys_con_macro_read_value_ |= (v&0x1)<<11; \
	MA_OUTW(cdc_control_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_cdc_control_NLR_BYPASS_347(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(cdc_control_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>11)&0x1; \
}

#define _GET_SYSCON_REG_pll1_config_LKDT_218(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll1_config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>0)&0x1; \
}

#define _SET_SYSCON_REG_pll1_config_N_218(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll1_config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x1E; \
	_sys_con_macro_read_value_ |= (v&0xF)<<1; \
	MA_OUTW(pll1_config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_pll1_config_N_218(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll1_config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>1)&0xF; \
}

#define _SET_SYSCON_REG_pll1_config_M_218(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll1_config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x1FE0; \
	_sys_con_macro_read_value_ |= (v&0xFF)<<5; \
	MA_OUTW(pll1_config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_pll1_config_M_218(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll1_config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>5)&0xFF; \
}

#define _SET_SYSCON_REG_pll1_config_PDRST_218(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll1_config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x2000; \
	_sys_con_macro_read_value_ |= (v&0x1)<<13; \
	MA_OUTW(pll1_config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_pll1_config_PDRST_218(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll1_config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>13)&0x1; \
}

#define _SET_SYSCON_REG_pll1_config_OD_218(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll1_config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0xC000; \
	_sys_con_macro_read_value_ |= (v&0x3)<<14; \
	MA_OUTW(pll1_config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_pll1_config_OD_218(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll1_config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>14)&0x3; \
}

#define _SET_SYSCON_REG_pll1_config_BP_218(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll1_config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x10000; \
	_sys_con_macro_read_value_ |= (v&0x1)<<16; \
	MA_OUTW(pll1_config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_pll1_config_BP_218(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll1_config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>16)&0x1; \
}

#define _GET_SYSCON_REG_pll2_config_LKDT_219(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll2_config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>0)&0x1; \
}

#define _SET_SYSCON_REG_pll2_config_N_219(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll2_config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x1E; \
	_sys_con_macro_read_value_ |= (v&0xF)<<1; \
	MA_OUTW(pll2_config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_pll2_config_N_219(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll2_config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>1)&0xF; \
}

#define _SET_SYSCON_REG_pll2_config_M_219(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll2_config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x1FE0; \
	_sys_con_macro_read_value_ |= (v&0xFF)<<5; \
	MA_OUTW(pll2_config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_pll2_config_M_219(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll2_config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>5)&0xFF; \
}

#define _SET_SYSCON_REG_pll2_config_PDRST_219(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll2_config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x2000; \
	_sys_con_macro_read_value_ |= (v&0x1)<<13; \
	MA_OUTW(pll2_config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_pll2_config_PDRST_219(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll2_config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>13)&0x1; \
}

#define _SET_SYSCON_REG_pll2_config_OD_219(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll2_config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0xC000; \
	_sys_con_macro_read_value_ |= (v&0x3)<<14; \
	MA_OUTW(pll2_config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_pll2_config_OD_219(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll2_config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>14)&0x3; \
}

#define _SET_SYSCON_REG_pll2_config_BP_219(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll2_config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x10000; \
	_sys_con_macro_read_value_ |= (v&0x1)<<16; \
	MA_OUTW(pll2_config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_pll2_config_BP_219(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll2_config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>16)&0x1; \
}

#define _GET_SYSCON_REG_pll3_config_LKDT_220(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll3_config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>0)&0x1; \
}

#define _SET_SYSCON_REG_pll3_config_N_220(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll3_config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x1E; \
	_sys_con_macro_read_value_ |= (v&0xF)<<1; \
	MA_OUTW(pll3_config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_pll3_config_N_220(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll3_config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>1)&0xF; \
}

#define _SET_SYSCON_REG_pll3_config_M_220(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll3_config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x1FE0; \
	_sys_con_macro_read_value_ |= (v&0xFF)<<5; \
	MA_OUTW(pll3_config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_pll3_config_M_220(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll3_config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>5)&0xFF; \
}

#define _SET_SYSCON_REG_pll3_config_PDRST_220(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll3_config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x2000; \
	_sys_con_macro_read_value_ |= (v&0x1)<<13; \
	MA_OUTW(pll3_config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_pll3_config_PDRST_220(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll3_config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>13)&0x1; \
}

#define _SET_SYSCON_REG_pll3_config_OD_220(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll3_config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0xC000; \
	_sys_con_macro_read_value_ |= (v&0x3)<<14; \
	MA_OUTW(pll3_config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_pll3_config_OD_220(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll3_config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>14)&0x3; \
}

#define _SET_SYSCON_REG_pll3_config_BP_220(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll3_config_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x10000; \
	_sys_con_macro_read_value_ |= (v&0x1)<<16; \
	MA_OUTW(pll3_config_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_pll3_config_BP_220(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pll3_config_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>16)&0x1; \
}

#define _SET_SYSCON_REG_pmu_system_power_switch_in_294(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pmu_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x1; \
	_sys_con_macro_read_value_ |= (v&0x1)<<0; \
	MA_OUTW(pmu_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_pmu_system_power_switch_in_294(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pmu_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>0)&0x1; \
}

#define _SET_SYSCON_REG_pmu_sram1_power_switch_in_294(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pmu_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x2; \
	_sys_con_macro_read_value_ |= (v&0x1)<<1; \
	MA_OUTW(pmu_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_pmu_sram1_power_switch_in_294(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pmu_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>1)&0x1; \
}

#define _SET_SYSCON_REG_pmu_sram2_power_switch_in_294(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pmu_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x4; \
	_sys_con_macro_read_value_ |= (v&0x1)<<2; \
	MA_OUTW(pmu_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_pmu_sram2_power_switch_in_294(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pmu_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>2)&0x1; \
}

#define _SET_SYSCON_REG_pmu_sram3_power_switch_in_294(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pmu_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x8; \
	_sys_con_macro_read_value_ |= (v&0x1)<<3; \
	MA_OUTW(pmu_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_pmu_sram3_power_switch_in_294(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pmu_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>3)&0x1; \
}

#define _SET_SYSCON_REG_pmu_dsp1_power_switch_in_294(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pmu_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x10; \
	_sys_con_macro_read_value_ |= (v&0x1)<<4; \
	MA_OUTW(pmu_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_pmu_dsp1_power_switch_in_294(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pmu_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>4)&0x1; \
}

#define _SET_SYSCON_REG_pmu_int_wakeup_enable_294(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pmu_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x3E0; \
	_sys_con_macro_read_value_ |= (v&0x1F)<<5; \
	MA_OUTW(pmu_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_pmu_int_wakeup_enable_294(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(pmu_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>5)&0x1F; \
}

#define _SET_SYSCON_REG_interrupt_control_interrupt_en_227(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(interrupt_control_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x1; \
	_sys_con_macro_read_value_ |= (v&0x1)<<0; \
	MA_OUTW(interrupt_control_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_interrupt_control_interrupt_en_227(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(interrupt_control_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>0)&0x1; \
}

#define _SET_SYSCON_REG_dma_req_control_ep1_switch_331(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dma_req_control_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x1; \
	_sys_con_macro_read_value_ |= (v&0x1)<<0; \
	MA_OUTW(dma_req_control_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dma_req_control_ep1_switch_331(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dma_req_control_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>0)&0x1; \
}

#define _SET_SYSCON_REG_dma_req_control_ep2_switch_332(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dma_req_control_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x2; \
	_sys_con_macro_read_value_ |= (v&0x1)<<1; \
	MA_OUTW(dma_req_control_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dma_req_control_ep2_switch_332(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dma_req_control_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>1)&0x1; \
}

#define _SET_SYSCON_REG_dma_req_control_ep3_switch_333(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dma_req_control_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x4; \
	_sys_con_macro_read_value_ |= (v&0x1)<<2; \
	MA_OUTW(dma_req_control_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dma_req_control_ep3_switch_333(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dma_req_control_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>2)&0x1; \
}

#define _SET_SYSCON_REG_debug_register_debug_field(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(debug_register_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0xFFFFFFFF; \
	_sys_con_macro_read_value_ |= (v&0xFFFFFFFF)<<0; \
	MA_OUTW(debug_register_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_debug_register_debug_field(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(debug_register_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>0)&0xFFFFFFFF; \
}

#define _SET_SYSCON_REG_osc_pad_control_OSC_DS0_272(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(osc_pad_control_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x1; \
	_sys_con_macro_read_value_ |= (v&0x1)<<0; \
	MA_OUTW(osc_pad_control_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_osc_pad_control_OSC_DS0_272(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(osc_pad_control_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>0)&0x1; \
}

#define _SET_SYSCON_REG_osc_pad_control_OSC_DS1_272(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(osc_pad_control_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x2; \
	_sys_con_macro_read_value_ |= (v&0x1)<<1; \
	MA_OUTW(osc_pad_control_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_osc_pad_control_OSC_DS1_272(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(osc_pad_control_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>1)&0x1; \
}

#define _SET_SYSCON_REG_i2s1_control_i2s1_mode_346(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(i2s1_control_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x1; \
	_sys_con_macro_read_value_ |= (v&0x1)<<0; \
	MA_OUTW(i2s1_control_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_i2s1_control_i2s1_mode_346(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(i2s1_control_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>0)&0x1; \
}

#define _SET_SYSCON_REG_i2s1_control_i2s1_enable_346(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(i2s1_control_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x2; \
	_sys_con_macro_read_value_ |= (v&0x1)<<1; \
	MA_OUTW(i2s1_control_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_i2s1_control_i2s1_enable_346(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(i2s1_control_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>1)&0x1; \
}

#define _SET_SYSCON_REG_i2s1_control_i2s_wrap_bypass_346(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(i2s1_control_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x4; \
	_sys_con_macro_read_value_ |= (v&0x1)<<2; \
	MA_OUTW(i2s1_control_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_i2s1_control_i2s_wrap_bypass_346(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(i2s1_control_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>2)&0x1; \
}

#define _SET_SYSCON_REG_i2s1_control_audio_mode_346(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(i2s1_control_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0xF0; \
	_sys_con_macro_read_value_ |= (v&0xF)<<4; \
	MA_OUTW(i2s1_control_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_i2s1_control_audio_mode_346(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(i2s1_control_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>4)&0xF; \
}

#define _SET_SYSCON_REG_i2s1_control_skip_head_346(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(i2s1_control_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0xFF00; \
	_sys_con_macro_read_value_ |= (v&0xFF)<<8; \
	MA_OUTW(i2s1_control_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_i2s1_control_skip_head_346(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(i2s1_control_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>8)&0xFF; \
}

#define _SET_SYSCON_REG_i2s1_control_lr_ratio_346(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(i2s1_control_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0xFF0000; \
	_sys_con_macro_read_value_ |= (v&0xFF)<<16; \
	MA_OUTW(i2s1_control_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_i2s1_control_lr_ratio_346(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(i2s1_control_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>16)&0xFF; \
}

#define _SET_SYSCON_REG_i2s1_control_slot_num_346(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(i2s1_control_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0xFF000000; \
	_sys_con_macro_read_value_ |= (v&0xFF)<<24; \
	MA_OUTW(i2s1_control_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_i2s1_control_slot_num_346(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(i2s1_control_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>24)&0xFF; \
}

#define _SET_SYSCON_REG_i2s1_delay_control_sdo_dly_cycle_346(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(i2s1_delay_control_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0xFF; \
	_sys_con_macro_read_value_ |= (v&0xFF)<<0; \
	MA_OUTW(i2s1_delay_control_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_i2s1_delay_control_sdo_dly_cycle_346(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(i2s1_delay_control_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>0)&0xFF; \
}

#define _SET_SYSCON_REG_i2s1_delay_control_lrck_dly_cycle_346(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(i2s1_delay_control_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x3F00; \
	_sys_con_macro_read_value_ |= (v&0x3F)<<8; \
	MA_OUTW(i2s1_delay_control_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_i2s1_delay_control_lrck_dly_cycle_346(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(i2s1_delay_control_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>8)&0x3F; \
}

#define _SET_SYSCON_REG_dsp0_mem_delay_delay_X128Y4D32B4_295(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0_mem_delay_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x3; \
	_sys_con_macro_read_value_ |= (v&0x3)<<0; \
	MA_OUTW(dsp0_mem_delay_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp0_mem_delay_delay_X128Y4D32B4_295(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0_mem_delay_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>0)&0x3; \
}

#define _SET_SYSCON_REG_dsp0_mem_delay_delay_X16Y4D69B2_295(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0_mem_delay_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x30; \
	_sys_con_macro_read_value_ |= (v&0x3)<<4; \
	MA_OUTW(dsp0_mem_delay_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp0_mem_delay_delay_X16Y4D69B2_295(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0_mem_delay_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>4)&0x3; \
}

#define _SET_SYSCON_REG_dsp0_mem_delay_delay_X256Y4D32B4_295(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0_mem_delay_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x300; \
	_sys_con_macro_read_value_ |= (v&0x3)<<8; \
	MA_OUTW(dsp0_mem_delay_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp0_mem_delay_delay_X256Y4D32B4_295(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0_mem_delay_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>8)&0x3; \
}

#define _SET_SYSCON_REG_dsp0_mem_delay_delay_X32Y4D29B2_295(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0_mem_delay_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x3000; \
	_sys_con_macro_read_value_ |= (v&0x3)<<12; \
	MA_OUTW(dsp0_mem_delay_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp0_mem_delay_delay_X32Y4D29B2_295(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0_mem_delay_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>12)&0x3; \
}

#define _SET_SYSCON_REG_dsp0_mem_delay_delay_X512Y8D64B4_295(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0_mem_delay_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x30000; \
	_sys_con_macro_read_value_ |= (v&0x3)<<16; \
	MA_OUTW(dsp0_mem_delay_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp0_mem_delay_delay_X512Y8D64B4_295(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0_mem_delay_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>16)&0x3; \
}

#define _SET_SYSCON_REG_dsp0_mem_delay_delay_X64Y4D64B2_295(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0_mem_delay_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x300000; \
	_sys_con_macro_read_value_ |= (v&0x3)<<20; \
	MA_OUTW(dsp0_mem_delay_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp0_mem_delay_delay_X64Y4D64B2_295(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0_mem_delay_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>20)&0x3; \
}

#define _SET_SYSCON_REG_dsp0_mem_delay_delay_X256Y8D32B4_295(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0_mem_delay_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x3000000; \
	_sys_con_macro_read_value_ |= (v&0x3)<<24; \
	MA_OUTW(dsp0_mem_delay_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp0_mem_delay_delay_X256Y8D32B4_295(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp0_mem_delay_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>24)&0x3; \
}

#define _SET_SYSCON_REG_dsp1_mem_delay_delay_X128Y4D32B4_296(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1_mem_delay_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x3; \
	_sys_con_macro_read_value_ |= (v&0x3)<<0; \
	MA_OUTW(dsp1_mem_delay_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp1_mem_delay_delay_X128Y4D32B4_296(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1_mem_delay_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>0)&0x3; \
}

#define _SET_SYSCON_REG_dsp1_mem_delay_delay_X16Y4D69B2_296(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1_mem_delay_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x30; \
	_sys_con_macro_read_value_ |= (v&0x3)<<4; \
	MA_OUTW(dsp1_mem_delay_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp1_mem_delay_delay_X16Y4D69B2_296(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1_mem_delay_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>4)&0x3; \
}

#define _SET_SYSCON_REG_dsp1_mem_delay_delay_X256Y4D32B4_296(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1_mem_delay_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x300; \
	_sys_con_macro_read_value_ |= (v&0x3)<<8; \
	MA_OUTW(dsp1_mem_delay_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp1_mem_delay_delay_X256Y4D32B4_296(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1_mem_delay_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>8)&0x3; \
}

#define _SET_SYSCON_REG_dsp1_mem_delay_delay_X32Y4D29B2_296(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1_mem_delay_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x3000; \
	_sys_con_macro_read_value_ |= (v&0x3)<<12; \
	MA_OUTW(dsp1_mem_delay_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp1_mem_delay_delay_X32Y4D29B2_296(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1_mem_delay_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>12)&0x3; \
}

#define _SET_SYSCON_REG_dsp1_mem_delay_delay_X512Y8D64B4_296(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1_mem_delay_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x30000; \
	_sys_con_macro_read_value_ |= (v&0x3)<<16; \
	MA_OUTW(dsp1_mem_delay_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp1_mem_delay_delay_X512Y8D64B4_296(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1_mem_delay_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>16)&0x3; \
}

#define _SET_SYSCON_REG_dsp1_mem_delay_delay_X64Y4D64B2_296(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1_mem_delay_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x300000; \
	_sys_con_macro_read_value_ |= (v&0x3)<<20; \
	MA_OUTW(dsp1_mem_delay_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp1_mem_delay_delay_X64Y4D64B2_296(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1_mem_delay_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>20)&0x3; \
}

#define _SET_SYSCON_REG_dsp1_mem_delay_delay_X256Y8D32B4_296(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1_mem_delay_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0x3000000; \
	_sys_con_macro_read_value_ |= (v&0x3)<<24; \
	MA_OUTW(dsp1_mem_delay_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_dsp1_mem_delay_delay_X256Y8D32B4_296(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(dsp1_mem_delay_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>24)&0x3; \
}

#define _SET_SYSCON_REG_power_up_delay_control_power_up_dly_294(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(power_up_delay_control_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0xFFFF; \
	_sys_con_macro_read_value_ |= (v&0xFFFF)<<0; \
	MA_OUTW(power_up_delay_control_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_power_up_delay_control_power_up_dly_294(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(power_up_delay_control_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>0)&0xFFFF; \
}

#define _SET_SYSCON_REG_power_down_delay_control_power_dn_dly_294(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(power_down_delay_control_REG_ADDR); \
	_sys_con_macro_read_value_ &= ~0xFFFF; \
	_sys_con_macro_read_value_ |= (v&0xFFFF)<<0; \
	MA_OUTW(power_down_delay_control_REG_ADDR,_sys_con_macro_read_value_); \
}

#define _GET_SYSCON_REG_power_down_delay_control_power_dn_dly_294(v) { \
	uint32_t _sys_con_macro_read_value_=MA_INW(power_down_delay_control_REG_ADDR); \
	v = (_sys_con_macro_read_value_>>0)&0xFFFF; \
}

#endif //_SYS_CON_MACRO_H_
